-- H2 2.1.212;
;             
CREATE USER IF NOT EXISTS "ADMIN" SALT '7a02689c94c7133e' HASH 'bf319dede8d2067671146ab91396882671d2779f093093b484373af3b616a73c' ADMIN;      
CREATE USER IF NOT EXISTS "IGRPWEB" SALT '63f694036c5f7e93' HASH 'ad8947847cae4672fbd275f24b9aa7abc01791b3393068ede0ca690741829215' ADMIN;    
CREATE CACHED TABLE "PUBLIC"."TBL_SESSION"(
    "ID" INTEGER GENERATED BY DEFAULT AS IDENTITY(START WITH 1) DEFAULT ON NULL NOT NULL,
    "ENDTIME" BIGINT,
    "HOST" CHARACTER VARYING(255),
    "HOSTNAME" CHARACTER VARYING(255),
    "HTTPS" INTEGER NOT NULL,
    "IPADDRESS" CHARACTER VARYING(255),
    "MEDIATYPE" CHARACTER VARYING(255),
    "SESSIONID" CHARACTER VARYING(255),
    "SESSIONOLDID" CHARACTER VARYING(255),
    "STARTTIME" BIGINT,
    "TARGET" CHARACTER VARYING(255),
    "URL" CHARACTER VARYING(255),
    "USERNAME" CHARACTER VARYING(255),
    "ENV_FK" INTEGER NOT NULL,
    "ORG_FK" INTEGER,
    "PROF_TYPE_FK" INTEGER NOT NULL,
    "USER_FK" INTEGER
);             
ALTER TABLE "PUBLIC"."TBL_SESSION" ADD CONSTRAINT "PUBLIC"."CONSTRAINT_7F6" PRIMARY KEY("ID");
-- 0 +/- SELECT COUNT(*) FROM PUBLIC.TBL_SESSION;             
CREATE CACHED TABLE "PUBLIC"."GLB_T_ACL"(
    "ID" INTEGER GENERATED BY DEFAULT AS IDENTITY(START WITH 1) DEFAULT ON NULL NOT NULL,
    "PROCESSKEY" CHARACTER VARYING(255),
    "STATUS" INTEGER NOT NULL,
    "TASKKEY" CHARACTER VARYING(255),
    "TYPE" CHARACTER VARYING(255),
    "TYPE_FK" INTEGER NOT NULL,
    "ENV_FK" INTEGER,
    "ENV_OWNER_FK" INTEGER
);             
ALTER TABLE "PUBLIC"."GLB_T_ACL" ADD CONSTRAINT "PUBLIC"."CONSTRAINT_4" PRIMARY KEY("ID");    
-- 0 +/- SELECT COUNT(*) FROM PUBLIC.GLB_T_ACL;               
CREATE CACHED TABLE "PUBLIC"."TBL_ACTION"(
    "ID" INTEGER GENERATED BY DEFAULT AS IDENTITY(START WITH 84) DEFAULT ON NULL NOT NULL,
    "ACTION" CHARACTER VARYING(255) NOT NULL,
    "ACTION_DESCR" CHARACTER VARYING(255),
    "ISCOMPONENT" SMALLINT NOT NULL,
    "NOMEMODULO" CHARACTER VARYING(255),
    "PACKAGE_NAME" CHARACTER VARYING(255),
    "PAGE" CHARACTER VARYING(255) NOT NULL,
    "PAGE_DESCR" CHARACTER VARYING(255),
    "PROCESSKEY" CHARACTER VARYING(255),
    "STATUS" INTEGER NOT NULL,
    "TIPO" SMALLINT NOT NULL,
    "VERSAO" CHARACTER VARYING(255),
    "XMLCONTENT" CHARACTER VARYING(255),
    "XSLCONTENT" CHARACTER VARYING(255),
    "XSL_SRC" CHARACTER VARYING(255),
    "ENV_FK" INTEGER NOT NULL
);             
ALTER TABLE "PUBLIC"."TBL_ACTION" ADD CONSTRAINT "PUBLIC"."CONSTRAINT_4C" PRIMARY KEY("ID");  
-- 83 +/- SELECT COUNT(*) FROM PUBLIC.TBL_ACTION;             
INSERT INTO "PUBLIC"."TBL_ACTION" VALUES
(1, 'index', 'Page builder', 0, NULL, 'nosi.webapps.igrp_studio.pages.listapage', 'ListaPage', 'Page builder', NULL, 1, 0, '2.3', NULL, NULL, 'igrp_studio/listapage/ListaPage.xsl', 3),
(2, 'index', 'Registar Aplicacao', 0, NULL, 'nosi.webapps.igrp_studio.pages.env', 'Env', 'Registar Aplicacao', NULL, 1, 0, '2.3', NULL, NULL, 'igrp_studio/env/Env.xsl', 3),
(3, 'index', 'Application builder', 0, NULL, 'nosi.webapps.igrp_studio.pages.listaenv', 'ListaEnv', 'Application builder', NULL, 1, 0, '2.3', NULL, NULL, 'igrp_studio/listaenv/ListaEnv.xsl', 3),
(4, 'index', U&'Gest\00e3o de Dom\00ednios', 0, NULL, 'nosi.webapps.igrp.pages.dominio', 'Dominio', U&'Gest\00e3o de Dom\00ednios', NULL, 1, 0, '2.3', NULL, NULL, 'igrp/dominio/Dominio.xsl', 1),
(5, 'index', 'Registar Dominio', 0, NULL, 'nosi.webapps.igrp.pages.novodominio', 'NovoDominio', 'Registar Dominio', NULL, 1, 0, '2.3', NULL, NULL, 'igrp/novodominio/NovoDominio.xsl', 1),
(6, 'index', U&'Gest\00e3o de Organica', 0, NULL, 'nosi.webapps.igrp.pages.pesquisarorganica', 'PesquisarOrganica', U&'Gest\00e3o de Organica', NULL, 1, 0, '2.3', NULL, NULL, 'igrp/pesquisarorganica/PesquisarOrganica.xsl', 1),
(7, 'index', 'Registar Organica', 0, NULL, 'nosi.webapps.igrp.pages.novaorganica', 'NovaOrganica', 'Registar Organica', NULL, 1, 0, '2.3', NULL, NULL, 'igrp/novaorganica/NovaOrganica.xsl', 1),
(8, 'index', 'Registar Menu', 0, NULL, 'nosi.webapps.igrp.pages.novomenu', 'NovoMenu', 'Registar Menu', NULL, 1, 0, '2.3', NULL, NULL, 'igrp/novomenu/NovoMenu.xsl', 1),
(9, 'index', U&'Gest\00e3o de Menu', 0, NULL, 'nosi.webapps.igrp.pages.pesquisarmenu', 'PesquisarMenu', U&'Gest\00e3o de Menu', NULL, 1, 0, '2.3', NULL, NULL, 'igrp/pesquisarmenu/PesquisarMenu.xsl', 1),
(10, 'index', 'Registar Perfil', 0, NULL, 'nosi.webapps.igrp.pages.novoperfil', 'NovoPerfil', 'Registar Perfil', NULL, 1, 0, '2.3', NULL, NULL, 'igrp/novoperfil/NovoPerfil.xsl', 1),
(11, 'index', U&'Gest\00e3o de Perfil', 0, NULL, 'nosi.webapps.igrp.pages.pesquisarperfil', 'PesquisarPerfil', U&'Gest\00e3o de Perfil', NULL, 1, 0, '2.3', NULL, NULL, 'igrp/pesquisarperfil/PesquisarPerfil.xsl', 1),
(12, 'index', U&'Gest\00e3o de Utilizador', 0, NULL, 'nosi.webapps.igrp.pages.pesquisarutilizador', 'PesquisarUtilizador', U&'Gest\00e3o de Utilizador', NULL, 1, 0, '2.3', NULL, NULL, 'igrp/pesquisarutilizador/PesquisarUtilizador.xsl', 1),
(13, 'index', 'Convidar Utilizador', 0, NULL, 'nosi.webapps.igrp.pages.novoutilizador', 'NovoUtilizador', 'Convidar Utilizador', NULL, 1, 0, '2.3', NULL, NULL, 'igrp/novoutilizador/NovoUtilizador.xsl', 1),
(14, 'index', U&'\00c1rea pessoal', 0, NULL, 'nosi.webapps.igrp.pages.settings', 'Settings', U&'\00c1rea pessoal', NULL, 1, 0, '2.3', NULL, NULL, 'igrp/settings/Settings.xsl', 1),
(15, 'index', 'Registar Utilizador', 0, NULL, 'nosi.webapps.igrp.pages.registarutilizador', 'RegistarUtilizador', 'Registar Utilizador', NULL, 1, 0, '2.3', NULL, NULL, 'igrp/registarutilizador/RegistarUtilizador.xsl', 1),
(16, 'index', 'Transaccao', 0, NULL, 'nosi.webapps.igrp.pages.transaccao', 'Transaccao', 'Transaccao', NULL, 1, 0, '2.3', NULL, NULL, 'igrp/transaccao/Transaccao.xsl', 1),
(17, 'index', 'Registar Pagina', 0, NULL, 'nosi.webapps.igrp.pages.page', 'Page', 'Registar Pagina', NULL, 1, 0, '2.3', NULL, NULL, 'igrp/page/Page.xsl', 1),
(18, 'index', 'Associar Menu a Organica', 0, NULL, 'nosi.webapps.igrp.pages.menuorganica', 'MenuOrganica', 'Associar Menu a Organica', NULL, 1, 0, '2.3', NULL, NULL, 'igrp/menuorganica/MenuOrganica.xsl', 1),
(19, 'index', 'Pagina de Erro', 0, NULL, 'nosi.webapps.igrp.pages.errorpage', 'ErrorPage', 'Pagina de Erro', NULL, 1, 1, '2.3', NULL, NULL, 'igrp/errorpage/ErrorPage.xsl', 1),
(20, 'index', 'Associar Transacao a Organica', 0, NULL, 'nosi.webapps.igrp.pages.transacaoorganica', 'TransacaoOrganica', 'Associar Transacao a Organica', NULL, 1, 0, '2.3', NULL, NULL, 'igrp/transacaoorganica/TransacaoOrganica.xsl', 1),
(21, 'index', 'Editar Transacao', 0, NULL, 'nosi.webapps.igrp.pages.editartransacao', 'EditarTransacao', 'Editar Transacao', NULL, 1, 0, '2.3', NULL, NULL, 'igrp/editartransacao/EditarTransacao.xsl', 1);
INSERT INTO "PUBLIC"."TBL_ACTION" VALUES
(22, 'index', 'Gestao de Sessao', 0, NULL, 'nosi.webapps.igrp.pages.session', 'Session', 'Gestao de Sessao', NULL, 1, 0, '2.3', NULL, NULL, 'igrp/session/Session.xsl', 1),
(23, 'index', 'Report Builder', 0, NULL, 'nosi.webapps.igrp_studio.pages.webreport', 'WebReport', 'Report Builder', NULL, 1, 0, '2.3', NULL, NULL, 'igrp_studio/webreport/WebReport.xsl', 3),
(24, 'index', 'Registar Data Source', 0, NULL, 'nosi.webapps.igrp.pages.datasource', 'DataSource', 'Registar Data Source', NULL, 1, 0, '2.3', NULL, NULL, 'igrp/datasource/DataSource.xsl', 1),
(25, 'index', 'Lista de Pagina Para Lookup', 0, NULL, 'nosi.webapps.igrp.pages.lookuplistpage', 'LookupListPage', 'Lista de Pagina Para Lookup', NULL, 1, 0, '2.3', NULL, NULL, 'igrp/lookuplistpage/LookupListPage.xsl', 1),
(26, 'index', 'Migrate IGRP', 0, NULL, 'nosi.webapps.igrp.pages.migrate', 'Migrate', 'Migrate IGRP', NULL, 1, 0, '2.3', NULL, NULL, 'igrp/migrate/Migrate.xsl', 1),
(27, 'index', 'Lista de credenciais OAuth', 0, NULL, 'nosi.webapps.igrp.pages.oauthclientlist', 'OAuthClientList', 'Lista de credenciais OAuth', NULL, 1, 0, '2.3', NULL, NULL, 'igrp/oauthclientlist/OAuthClientList.xsl', 1),
(28, 'index', 'Registar cliente OAuth', 0, NULL, 'nosi.webapps.igrp.pages.oauthclient', 'OAuthClient', 'Registar cliente OAuth', NULL, 1, 0, '2.3', NULL, NULL, 'igrp/oauthclient/OAuthClient.xsl', 1),
(29, 'index', 'Mapa Processo', 0, NULL, 'nosi.webapps.igrp.pages.mapaprocesso', 'MapaProcesso', 'Mapa Processo', NULL, 1, 0, '2.3', NULL, NULL, 'igrp/mapaprocesso/MapaProcesso.xsl', 1),
(30, 'index', 'Execucao Tarefas', 0, NULL, 'nosi.webapps.igrp.pages.execucaotarefas', 'ExecucaoTarefas', 'Execucao Tarefas', NULL, 1, 0, '2.3', NULL, NULL, 'igrp/execucaotarefas/ExecucaoTarefas.xsl', 1),
(31, 'index', 'Lookup Lista Utilizador', 0, NULL, 'nosi.webapps.igrp.pages.lookuplistuser', 'LookupListUser', 'Lookup Lista Utilizador', NULL, 1, 0, '2.3', NULL, NULL, 'igrp/lookuplistuser/LookupListUser.xsl', 1),
(32, 'index', 'Alter prioridade tarefa', 0, NULL, 'nosi.webapps.igrp.pages.alter_prioridade_tarefa', 'Alter_prioridade_tarefa', 'Alter prioridade tarefa', NULL, 1, 0, '2.3', NULL, NULL, 'igrp/alter_prioridade_tarefa/Alter_prioridade_tarefa.xsl', 1),
(33, 'index', 'Transferir tarefas', 0, NULL, 'nosi.webapps.igrp.pages.transferir_tarefas', 'Transferir_tarefas', 'Transferir tarefas', NULL, 1, 0, '2.3', NULL, NULL, 'igrp/transferir_tarefas/Transferir_tarefas.xsl', 1),
(34, 'index', 'BPMN Designer', 0, NULL, 'nosi.webapps.igrp_studio.pages.bpmndesigner', 'BPMNDesigner', 'BPMN Designer', NULL, 1, 0, '2.3', NULL, NULL, 'igrp_studio/bpmndesigner/BPMNDesigner.xsl', 3),
(35, 'index', 'Import export', 0, NULL, 'nosi.webapps.igrp.pages.import_export', 'Import_export', 'Import export', NULL, 1, 0, '2.3', NULL, NULL, 'igrp/import_export/Import_export.xsl', 1),
(36, 'index', 'Import Arquivo', 0, NULL, 'nosi.webapps.igrp_studio.pages.importarquivo', 'ImportArquivo', 'Import Arquivo', NULL, 1, 0, '2.3', NULL, NULL, 'igrp_studio/importarquivo/ImportArquivo.xsl', 3),
(37, 'index', U&'Configurar Base de Dados de uma aplica\00e7\00e3o', 0, NULL, 'nosi.webapps.igrp.pages.configdatabase', 'ConfigDatabase', 'Configurar Base de Dados', NULL, 1, 0, '2.3', NULL, NULL, 'igrp/configdatabase/ConfigDatabase.xsl', 1),
(38, 'index', 'Pesquisar BI', 0, NULL, 'nosi.webapps.igrp.pages.pesquisabi', 'PesquisaBI', 'Pesquisar BI', NULL, 1, 0, '2.3', NULL, NULL, 'igrp/pesquisabi/PesquisaBI.xsl', 1),
(39, 'index', 'Pesquisar NIF', 0, NULL, 'nosi.webapps.igrp.pages.pesquisanif', 'PesquisaNIF', 'Pesquisar NIF', NULL, 1, 0, '2.3', NULL, NULL, 'igrp/pesquisanif/PesquisaNIF.xsl', 1),
(40, 'index', 'Pesquisar Nascimento', 0, NULL, 'nosi.webapps.igrp.pages.pesquisanascimento', 'PesquisaNascimento', 'Pesquisar Nascimento', NULL, 1, 0, '2.3', NULL, NULL, 'igrp/pesquisanascimento/PesquisaNascimento.xsl', 1),
(41, 'index', 'Gestao de Acesso', 0, NULL, 'nosi.webapps.igrp.pages.gestaodeacesso', 'Gestaodeacesso', 'Gestao de Acesso', NULL, 1, 0, '2.3', NULL, NULL, 'igrp/gestaodeacesso/Gestaodeacesso.xsl', 1);       
INSERT INTO "PUBLIC"."TBL_ACTION" VALUES
(42, 'index', 'O que fazer dentro do IGRP JAVA...', 0, NULL, 'nosi.webapps.tutorial.pages.geralapresentacao', 'GeralApresentacao', 'O que fazer dentro do IGRP JAVA...', NULL, 1, 0, '2.3', NULL, NULL, 'tutorial/geralapresentacao/GeralApresentacao.xsl', 2),
(43, 'index', 'HomeStudio', 0, NULL, 'nosi.webapps.igrp_studio.pages.homestudio', 'HomeStudio', 'HomeStudio', NULL, 0, 0, '2.3', NULL, NULL, 'igrp_studio/homestudio/HomeStudio.xsl', 3),
(44, 'index', 'CRUD Generator', 0, NULL, 'nosi.webapps.igrp_studio.pages.crudgenerator', 'CRUDGenerator', 'CRUDGenerator', NULL, 1, 0, '2.3', NULL, NULL, 'igrp_studio/crudgenerator/CRUDGenerator.xsl', 3),
(45, 'index', 'LdapUser', 0, NULL, 'nosi.webapps.igrp.pages.ldapuser', 'LdapUser', 'LdapUser', NULL, 1, 0, '2.3', NULL, NULL, 'igrp/ldapuser/LdapUser.xsl', 1),
(46, 'index', 'ChangePassword', 0, NULL, 'nosi.webapps.igrp.pages.changepassword', 'ChangePassword', 'ChangePassword', NULL, 1, 0, '2.3', NULL, NULL, 'igrp/changepassword/ChangePassword.xsl', 1),
(47, 'index', 'Consulta Processo', 0, NULL, 'nosi.webapps.igrp.pages._cons_proc', '_CONS_PROC', 'Consulta Processo', NULL, 1, 0, '2.3', NULL, NULL, 'igrp/_cons_proc/_CONS_PROC.xsl', 1),
(48, 'index', 'Detalhes Processo', 0, NULL, 'nosi.webapps.igrp.pages.detalhesprocesso', 'DetalhesProcesso', 'Detalhes Processo', NULL, 1, 0, '2.3', NULL, NULL, 'igrp/detalhesprocesso/DetalhesProcesso.xsl', 1),
(49, 'index', U&'Partilha Inter-Aplica\00e7\00f5es', 0, NULL, 'nosi.webapps.igrp_studio.pages.partilhageral', 'Partilhageral', U&'Partilha Inter-Aplica\00e7\00f5es', NULL, 1, 0, '2.3', NULL, NULL, 'igrp_studio/partilhageral/Partilhageral.xsl', 3),
(50, 'index', U&'M\00f3dulo', 0, NULL, 'nosi.webapps.igrp_studio.pages.modulo', 'Modulo', U&'M\00f3dulo', NULL, 1, 0, '2.3', NULL, NULL, 'igrp_studio/modulo/Modulo.xsl', 3),
(51, 'index', 'Lookup list organica', 0, NULL, 'nosi.webapps.igrp.pages', 'Lookup_list_organica', 'Lookup list organica', NULL, 1, 0, '2.3', NULL, NULL, 'igrp/lookup_list_organica/Lookup_list_organica.xsl', 1),
(52, 'index', 'SQL Tool', 0, NULL, 'nosi.webapps.igrp_studio.pages', 'Sql_tools', 'SQL Tool', NULL, 1, 0, '2.3', NULL, NULL, 'igrp_studio/sql_tools/Sql_tools.xsl', 3),
(53, 'index', 'File', 0, NULL, 'nosi.webapps.igrp.pages', 'File', 'File', NULL, 1, 0, '2.3', NULL, NULL, 'igrp/file/File.xsl', 1),
(54, 'index', 'EtapaAccess', 0, NULL, 'nosi.webapps.igrp.pages', 'Etapaaccess', 'EtapaAccess', NULL, 1, 0, '2.3', NULL, NULL, 'igrp/etapaaccess/Etapaaccess.xsl', 1),
(55, 'index', 'AddFileTask', 0, NULL, 'nosi.webapps.igrp.pages', 'Addfiletask', 'AddFileTask', NULL, 1, 0, '2.3', NULL, NULL, 'igrp/addfiletask/Addfiletask.xsl', 1),
(56, 'index', U&'video gest\00e3o de aplica\00e7\00e3o', 0, NULL, 'nosi.webapps.tutorial.pages.video_gestao_de_aplicacao', 'Video_gestao_de_aplicacao', U&'video gest\00e3o de aplica\00e7\00e3o', NULL, 1, 0, '2.3', NULL, NULL, 'tutorial/video_gestao_de_aplicacao/Video_gestao_de_aplicacao.xsl', 2),
(57, 'index', 'video instalar igrp web', 0, NULL, 'nosi.webapps.tutorial.pages.video_instalar_igrp_web', 'Video_instalar_igrp_web', 'video instalar igrp web', NULL, 1, 0, '2.3', NULL, NULL, 'tutorial/video_instalar_igrp_web/Video_instalar_igrp_web.xsl', 2),
(58, 'index', 'video my first app', 0, NULL, 'nosi.webapps.tutorial.pages.video_my_first_app', 'Video_my_first_app', 'video my first app', NULL, 1, 0, '2.3', NULL, NULL, 'tutorial/video_my_first_app/Video_my_first_app.xsl', 2),
(59, 'index', 'File Editor', 0, NULL, 'nosi.webapps.igrp_studio.pages', 'File_editor', 'File Editor', NULL, 1, 0, '2.3', NULL, NULL, 'igrp_studio/file_editor/File_editor.xsl', 3),
(60, 'index', 'Gestao Tipo Documento', 0, NULL, 'nosi.webapps.igrp.pages', 'Gestao_tipo_documento', 'Gestao Tipo Documento', NULL, 1, 0, '2.3', NULL, NULL, 'igrp/gestao_tipo_documento/Gestao_tipo_documento.xsl', 1),
(61, 'index', 'Start Process', 0, NULL, 'nosi.webapps.igrp.pages', 'Startprocess', 'Start Process', NULL, 1, 0, '2.3', NULL, NULL, 'igrp/startprocess/Startprocess.xsl', 1),
(62, 'index', 'Default Page', 0, NULL, 'nosi.webapps.tutorial.pages', 'DefaultPage', 'Default Page', NULL, 1, 0, '2.3', NULL, NULL, 'tutorial/defaultpage/DefaultPage.xsl', 2); 
INSERT INTO "PUBLIC"."TBL_ACTION" VALUES
(63, 'index', 'Dash Board Processo', 0, NULL, 'nosi.webapps.igrp.pages', 'Dash_board_processo', 'Dash Board Processo', NULL, 1, 0, '2.3', NULL, NULL, 'igrp/dash_board_processo/Dash_board_processo.xsl', 1),
(64, 'index', 'Lista Tarefa de Processo', 0, NULL, 'nosi.webapps.igrp.pages', 'Lista_terfa_de_processo', 'Lista Tarefa de Processo', NULL, 1, 0, '2.3', NULL, NULL, 'igrp/lista_terfa_de_processo/Lista_terfa_de_processo.xsl', 1),
(65, 'index', 'Export Wizard Step 1', 0, NULL, 'nosi.webapps.igrp_studio.pages', 'Wizard_export_step_1', 'Export Wizard Step 1', NULL, 1, 0, '2.3', NULL, NULL, 'igrp_studio/wizard_export_step_1/Wizard_export_step_1.xsl', 3),
(66, 'index', 'Export Wizard Step 2', 0, NULL, 'nosi.webapps.igrp_studio.pages', 'Wizard_export_step_2', 'Export Wizard Step 2', NULL, 1, 0, '2.3', NULL, NULL, 'igrp_studio/wizard_export_step_2/Wizard_export_step_2.xsl', 3),
(67, 'index', 'Reset by email', 0, NULL, 'nosi.webapps.igrp.pages', 'Resetbyemail', 'Reset by email', NULL, 1, 1, '2.3', NULL, NULL, 'igrp/resetbyemail/Resetbyemail.xsl', 1),
(68, 'index', 'Reset password', 0, NULL, 'nosi.webapps.igrp.pages', 'Resetpassword', 'Reset password', NULL, 1, 1, '2.3', NULL, NULL, 'igrp/resetpassword/Resetpassword.xsl', 1),
(69, 'index', 'Oauth2openidwso2', 0, NULL, 'nosi.webapps.igrp.pages', 'Oauth2openidwso2', 'Oauth2openidwso2', NULL, 1, 1, '2.3', NULL, NULL, 'igrp/oauth2openidwso2/Oauth2openidwso2.xsl', 1),
(70, 'index', 'Pesquisa BI-CNI-passport', 0, NULL, 'nosi.webapps.igrp_studio.pages', 'Pesquisa_bi_cni_passport', 'Pesquisa BI-CNI-passport', NULL, 1, 0, '2.3', NULL, NULL, 'igrp_studio/pesquisa_bi_cni_passport/Pesquisa_bi_cni_passport.xsl', 3),
(71, 'index', 'Pesquisa NIF', 0, NULL, 'nosi.webapps.igrp_studio.pages', 'Pesquisa_nif_rest', 'Pesquisa NIF', NULL, 1, 0, '2.3', NULL, NULL, 'igrp_studio/pesquisa_nif_rest/Pesquisa_nif_rest.xsl', 3),
(72, 'index', 'Pesquisa Geografia', 0, NULL, 'nosi.webapps.igrp_studio.pages', 'Pesquisa_geografia', 'Pesquisa Geografia', NULL, 1, 1, '2.3', NULL, NULL, 'igrp_studio/pesquisa_geografia/Pesquisa_geografia.xsl', 3),
(73, 'index', 'Pesquisa nacionalidade', 0, NULL, 'nosi.webapps.igrp_studio.pages', 'Pesquisa_nacionalidade', 'Pesquisa nacionalidade', NULL, 1, 1, '2.3', NULL, NULL, 'igrp_studio/pesquisa_nacionalidade/Pesquisa_nacionalidade.xsl', 3),
(74, 'index', 'WSDL2java', 0, NULL, 'nosi.webapps.igrp_studio.pages', 'Wsdl2java', 'WSDL2java', NULL, 1, 0, '2.3', NULL, NULL, 'igrp_studio/wsdl2java/Wsdl2java.xsl', 3),
(75, 'index', 'Pesquisa Empresa', 0, NULL, 'nosi.webapps.igrp.pages', 'Pesquisa_empresa', 'Pesquisa Empresa', NULL, 1, 0, '2.3', NULL, NULL, 'igrp/pesquisa_empresa/Pesquisa_empresa.xsl', 1),
(76, 'index', 'DAOGenerator', 0, NULL, 'nosi.webapps.igrp_studio.pages', 'Daogenerator', 'DAOGenerator', NULL, 1, 0, '2.3', NULL, NULL, 'igrp_studio/daogenerator/Daogenerator.xsl', 3),
(77, 'index', 'Detalhes dashboard processo', 0, NULL, 'nosi.webapps.igrp.pages', 'Detalhes_dashboard_processo', 'Detalhes dashboard processo', NULL, 1, 0, '2.3', NULL, NULL, 'igrp/detalhes_dashboard_processo/Detalhes_dashboard_processo.xsl', 1),
(78, 'index', 'Historico_page', 0, NULL, 'nosi.webapps.igrp_studio.pages', 'Historico_page', 'Historico page', NULL, 1, 0, '2.3', NULL, NULL, 'igrp_studio/historico_page/Historico_page.xsl', 3),
(79, 'index', 'Icons list', 0, NULL, 'nosi.webapps.igrp.pages', 'Icons_list', 'Icons list', NULL, 1, 0, '2.3', NULL, NULL, 'igrp/icons_list/Icons_list.xsl', 1),
(80, 'index', 'Migration File Generator', 0, NULL, 'nosi.webapps.igrp_studio.pages', 'Migration', 'Migration File Generator', NULL, 1, 0, '2.3', NULL, NULL, 'igrp_studio/migration/Migration.xsl', 3),
(81, 'index', 'Get coordinates', 0, NULL, 'nosi.webapps.igrp_studio.pages', 'Get_coordinates', 'Get coordinates', NULL, 1, 0, '2.3', NULL, NULL, 'igrp_studio/get_coordinates/Get_coordinates.xsl', 3),
(82, 'index', 'Config error msg', 0, NULL, 'nosi.webapps.igrp_studio.pages', 'Config_error_msg', 'Config error msg', NULL, 1, 0, '2.3', NULL, NULL, 'igrp_studio/config_error_msg/Config_error_msg.xsl', 3);      
INSERT INTO "PUBLIC"."TBL_ACTION" VALUES
(83, 'index', 'Pesquisa CAE', 0, NULL, 'nosi.webapps.igrp.pages', 'Pesquisa_cae', 'Pesquisa CAE', NULL, 1, 0, '2.3', NULL, NULL, 'igrp/pesquisa_cae/Pesquisa_cae.xsl', 1);          
CREATE CACHED TABLE "PUBLIC"."TBL_ACTIVITY_EXECUTE"(
    "ID" INTEGER GENERATED BY DEFAULT AS IDENTITY(START WITH 1) DEFAULT ON NULL NOT NULL,
    "CUSTOM_PERMISSION" CHARACTER LARGE OBJECT,
    "EXECUTION_TYPE" CHARACTER VARYING(400) NOT NULL,
    "PROCCESS_KEY" CHARACTER VARYING(200) NOT NULL,
    "PROCESS_NAME" CHARACTER VARYING(250),
    "PROCESSID" CHARACTER VARYING(255) NOT NULL,
    "TASK_KEY" CHARACTER VARYING(200) NOT NULL,
    "TASKID" CHARACTER VARYING(255) NOT NULL,
    "UPDATEDATETIME" TIMESTAMP,
    "ENV_FK" INTEGER NOT NULL,
    "ORG_FK" INTEGER NOT NULL,
    "PROF_FK" INTEGER NOT NULL,
    "USER_FK" INTEGER
);       
ALTER TABLE "PUBLIC"."TBL_ACTIVITY_EXECUTE" ADD CONSTRAINT "PUBLIC"."CONSTRAINT_6" PRIMARY KEY("ID");         
-- 0 +/- SELECT COUNT(*) FROM PUBLIC.TBL_ACTIVITY_EXECUTE;    
CREATE CACHED TABLE "PUBLIC"."TBL_CLOB"(
    "ID" INTEGER GENERATED BY DEFAULT AS IDENTITY(START WITH 1) DEFAULT ON NULL NOT NULL,
    "C_LOB_CONTENT" BINARY(255) NOT NULL,
    "CREATEDATETIME" TIMESTAMP,
    "DT_CREATED" DATE NOT NULL,
    "DT_UPDATED" DATE,
    "ESTADO" CHARACTER VARYING(255),
    "MIME_TYPE" CHARACTER VARYING(255),
    "NAME" CHARACTER VARYING(255),
    "UPDATEDATETIME" TIMESTAMP,
    "UUID" CHARACTER VARYING(255),
    "ENV_FK" INTEGER,
    "ENV_UPDATED_FK" INTEGER,
    "USER_CREATED_FK" INTEGER
);     
ALTER TABLE "PUBLIC"."TBL_CLOB" ADD CONSTRAINT "PUBLIC"."CONSTRAINT_40" PRIMARY KEY("ID");    
-- 0 +/- SELECT COUNT(*) FROM PUBLIC.TBL_CLOB;
CREATE CACHED TABLE "PUBLIC"."TBL_CONFIG"(
    "ID" INTEGER GENERATED BY DEFAULT AS IDENTITY(START WITH 18) DEFAULT ON NULL NOT NULL,
    "NAME" CHARACTER VARYING(255) NOT NULL,
    "VALUE" CHARACTER VARYING(255) NOT NULL,
    "ENV_FK" INTEGER
);   
ALTER TABLE "PUBLIC"."TBL_CONFIG" ADD CONSTRAINT "PUBLIC"."CONSTRAINT_5" PRIMARY KEY("ID");   
-- 17 +/- SELECT COUNT(*) FROM PUBLIC.TBL_CONFIG;             
INSERT INTO "PUBLIC"."TBL_CONFIG" VALUES
(1, 'url_ativiti_connection', 'http://localhost:8080/activiti-rest/service/', NULL),
(2, 'ativiti_user', 'kermit', NULL),
(3, 'ativiti_password', 'kermit', NULL),
(4, 'igrp_images', 'IGRP', NULL),
(5, 'CLIENT_ID_BIZTALK', 'your id', NULL),
(6, 'TRANSACTION_ID_BIZTALK_PESQUISA_NIF', 'your id', NULL),
(7, 'SERVICE_ID_BIZTALK_PESQUISA_NIF', 'your id', NULL),
(8, 'TRANSACTION_ID_BIZTALK_PESQUISA_GEOGRAFIA', 'your id', NULL),
(9, 'SERVICE_ID_BIZTALK_PESQUISA_GEOGRAFIA', 'your id', NULL),
(10, 'TRANSACTION_ID_BIZTALK_PESQUISA_HIERARQUICA_CAE', 'your id', NULL),
(11, 'SERVICE_ID_BIZTALK_PESQUISA_HIERARQUICA_CAE', 'your id', NULL),
(12, 'TRANSACTION_ID_BIZTALK_PESQUISA_NASCIMENTO', 'your id', NULL),
(13, 'SERVICE_ID_BIZTALK_PESQUISA_NASCIMENTO', 'your id', NULL),
(14, 'TRANSACTION_ID_BIZTALK_PESQUISA_SNIAC', 'your id', NULL),
(15, 'SERVICE_ID_BIZTALK_PESQUISA_SNIAC', 'your id', NULL),
(16, 'TRANSACTION_ID_BIZTALK_PESQUISA_BI', 'your id', NULL),
(17, 'SERVICE_ID_BIZTALK_PESQUISA_BI', 'your id', NULL);     
CREATE CACHED TABLE "PUBLIC"."TBL_CONFIG_ENV"(
    "ID" INTEGER GENERATED BY DEFAULT AS IDENTITY(START WITH 1) DEFAULT ON NULL NOT NULL,
    "CHARSET" CHARACTER VARYING(255),
    "CONNECTION_IDENTIFY" CHARACTER VARYING(255),
    "DRIVER_CONNECTION" CHARACTER VARYING(255) NOT NULL,
    "HOST" CHARACTER VARYING(255),
    "ISDEFAULT" SMALLINT NOT NULL,
    "NAME" CHARACTER VARYING(255) NOT NULL,
    "NAME_DB" CHARACTER VARYING(255),
    "PASSWORD" CHARACTER VARYING(255) NOT NULL,
    "PORT" CHARACTER VARYING(255),
    "TYPE_DB" CHARACTER VARYING(255) NOT NULL,
    "URL_CONNECTION" CHARACTER VARYING(255) NOT NULL,
    "USERNAME" CHARACTER VARYING(255) NOT NULL,
    "ENV_FK" INTEGER NOT NULL
);     
ALTER TABLE "PUBLIC"."TBL_CONFIG_ENV" ADD CONSTRAINT "PUBLIC"."CONSTRAINT_7" PRIMARY KEY("ID");               
-- 0 +/- SELECT COUNT(*) FROM PUBLIC.TBL_CONFIG_ENV;          
CREATE CACHED TABLE "PUBLIC"."TBL_DOMAIN"(
    "ID" INTEGER GENERATED BY DEFAULT AS IDENTITY(START WITH 1) DEFAULT ON NULL NOT NULL,
    "DESCRIPTION" CHARACTER VARYING(250) NOT NULL,
    "DOMAIN_TYPE" CHARACTER VARYING(8),
    "DOMINIO" CHARACTER VARYING(100) NOT NULL,
    "ORDEM" INTEGER NOT NULL,
    "STATUS" CHARACTER VARYING(8) NOT NULL,
    "VALOR" CHARACTER VARYING(150) NOT NULL,
    "ENV_FK" INTEGER
);        
ALTER TABLE "PUBLIC"."TBL_DOMAIN" ADD CONSTRAINT "PUBLIC"."CONSTRAINT_52" PRIMARY KEY("ID");  
-- 0 +/- SELECT COUNT(*) FROM PUBLIC.TBL_DOMAIN;              
CREATE CACHED TABLE "PUBLIC"."TBL_ENV"(
    "ID" INTEGER GENERATED BY DEFAULT AS IDENTITY(START WITH 4) DEFAULT ON NULL NOT NULL,
    "DAD" CHARACTER VARYING(255) NOT NULL,
    "DESCRIPTION" CHARACTER VARYING(255),
    "EXTERNO" INTEGER NOT NULL,
    "IMG_SRC" CHARACTER VARYING(255),
    "NAME" CHARACTER VARYING(255) NOT NULL,
    "PLSQL_CODE" CHARACTER VARYING(255),
    "STATUS" INTEGER NOT NULL,
    "TEMPLATE" CHARACTER VARYING(255),
    "URL" CHARACTER VARYING(255),
    "ACTION_FK" INTEGER
);              
ALTER TABLE "PUBLIC"."TBL_ENV" ADD CONSTRAINT "PUBLIC"."CONSTRAINT_D" PRIMARY KEY("ID");      
-- 3 +/- SELECT COUNT(*) FROM PUBLIC.TBL_ENV; 
INSERT INTO "PUBLIC"."TBL_ENV" VALUES
(1, 'igrp', 'Integrated Government Resource Planning', 0, 'igrp.svg', 'IGRP', NULL, 1, NULL, NULL, NULL),
(2, 'tutorial', 'IGRPweb TODO', 0, 'icon_educacao.png', 'Tutorial IGRP', NULL, 1, NULL, NULL, 42),
(3, 'igrp_studio', '<code/> {Developers}', 0, 'studioSoLogo.svg', 'IGRP Studio', NULL, 1, 'igrp_studio', NULL, 1);      
CREATE CACHED TABLE "PUBLIC"."TBL_HISTORIC"(
    "ID" INTEGER GENERATED BY DEFAULT AS IDENTITY(START WITH 1) DEFAULT ON NULL NOT NULL,
    "COMENTARIO" CHARACTER VARYING(255),
    "DATA" TIMESTAMP,
    "DESCRICAO" CHARACTER VARYING(255) NOT NULL,
    "IDUTILIZADOR" INTEGER,
    "NOME" CHARACTER VARYING(255) NOT NULL,
    "PAGE_FK" INTEGER NOT NULL
);      
ALTER TABLE "PUBLIC"."TBL_HISTORIC" ADD CONSTRAINT "PUBLIC"."CONSTRAINT_53" PRIMARY KEY("ID");
-- 0 +/- SELECT COUNT(*) FROM PUBLIC.TBL_HISTORIC;            
CREATE CACHED TABLE "PUBLIC"."TBL_IMPORTEXPORT"(
    "ID" INTEGER GENERATED BY DEFAULT AS IDENTITY(START WITH 1) DEFAULT ON NULL NOT NULL,
    "APLICACAO" CHARACTER VARYING(255),
    "DATA" CHARACTER VARYING(255),
    "TIPO" CHARACTER VARYING(255),
    "USUARIO" CHARACTER VARYING(255)
);        
ALTER TABLE "PUBLIC"."TBL_IMPORTEXPORT" ADD CONSTRAINT "PUBLIC"."CONSTRAINT_E" PRIMARY KEY("ID");             
-- 0 +/- SELECT COUNT(*) FROM PUBLIC.TBL_IMPORTEXPORT;        
CREATE CACHED TABLE "PUBLIC"."TBL_MAPPING"(
    "ID" INTEGER GENERATED BY DEFAULT AS IDENTITY(START WITH 1) DEFAULT ON NULL NOT NULL,
    "DAD_DESTINO" CHARACTER VARYING(255),
    "DAD_ORIGEM" CHARACTER VARYING(255),
    "TIPO" INTEGER NOT NULL,
    "VALOR_DESTINO" CHARACTER VARYING(255),
    "VALOR_ORIGEM" CHARACTER VARYING(255)
);         
ALTER TABLE "PUBLIC"."TBL_MAPPING" ADD CONSTRAINT "PUBLIC"."CONSTRAINT_C" PRIMARY KEY("ID");  
-- 0 +/- SELECT COUNT(*) FROM PUBLIC.TBL_MAPPING;             
CREATE CACHED TABLE "PUBLIC"."TBL_MENU"(
    "ID" INTEGER GENERATED BY DEFAULT AS IDENTITY(START WITH 24) DEFAULT ON NULL NOT NULL,
    "DESCR" CHARACTER VARYING(255) NOT NULL,
    "FLG_BASE" INTEGER NOT NULL,
    "LINK" CHARACTER VARYING(2000),
    "MENU_ICON" CHARACTER VARYING(255),
    "ORDERBY" INTEGER NOT NULL,
    "STATUS" INTEGER NOT NULL,
    "TARGET" CHARACTER VARYING(255),
    "ACTION_FK" INTEGER,
    "ENV_FK" INTEGER NOT NULL,
    "SELF_FK" INTEGER
);
ALTER TABLE "PUBLIC"."TBL_MENU" ADD CONSTRAINT "PUBLIC"."CONSTRAINT_404" PRIMARY KEY("ID");   
-- 23 +/- SELECT COUNT(*) FROM PUBLIC.TBL_MENU;               
INSERT INTO "PUBLIC"."TBL_MENU" VALUES
(1, U&'Gest\00e3o de Aplica\00e7\00e3o', 0, NULL, NULL, 98, 1, NULL, NULL, 1, NULL),
(2, 'Parametros Gerais', 0, NULL, NULL, 98, 1, NULL, NULL, 1, NULL),
(3, 'Auditoria', 0, NULL, NULL, 98, 1, NULL, NULL, 1, NULL),
(4, 'IGRP Studio', 0, NULL, NULL, 1, 1, NULL, NULL, 3, NULL),
(5, 'Application Builder', 1, NULL, NULL, 98, 1, '_self', 3, 3, 4),
(6, 'Home - Page Builder', 0, NULL, NULL, 0, 1, '_self', 1, 3, 6),
(7, 'Report Designer', 0, NULL, NULL, 4, 1, '_self', 23, 3, 4),
(8, U&'Gest\00e3o de Menu', 0, NULL, NULL, 7, 0, '_self', 9, 1, 1),
(9, U&'Gest\00e3o de Transa\00e7\00e3o', 0, NULL, NULL, 8, 0, '_self', 16, 1, 1),
(10, U&'Gest\00e3o de Acesso', 1, NULL, NULL, 999, 1, '_self', 41, 1, 10),
(11, U&'Gest\00e3o de Utilizador', 0, NULL, NULL, 9, 0, '_self', 12, 1, 1),
(12, U&'\00c1rea Pessoal', 1, NULL, NULL, 1, 1, '_self', 14, 1, 12),
(13, 'BPMN Designer', 0, NULL, NULL, 1, 1, '_self', 34, 3, 4),
(14, 'CRUD Generator', 0, NULL, NULL, 1, 1, '_self', 44, 3, 4),
(15, 'Consultar Processo', 1, NULL, NULL, 90, 1, '_self', 47, 1, 15),
(16, 'OAuth Client Id', 0, NULL, NULL, 99, 0, '_self', 27, 1, 16),
(17, U&'Partilha Inter-Aplica\00e7\00f5es', 1, NULL, NULL, 98, 1, '_self', 49, 3, 17),
(18, 'SQL Tool', 0, NULL, NULL, 99, 1, 'modal', 52, 3, 18),
(19, 'Migrate IGRP', 0, NULL, NULL, 99, 1, '_self', 26, 1, 19),
(20, 'Gestao tipo documento', 0, NULL, NULL, 99, 1, '_self', 60, 1, 20),
(21, U&'Gest\00e3o de Dom\00ednio', 1, NULL, NULL, 99, 1, '_self', 4, 1, 21),
(22, 'WSDL2Java', 0, NULL, NULL, 99, 1, 'modal', 74, 3, 22),
(23, 'Migration File Generator', 0, NULL, NULL, 10, 1, '_self', 80, 3, 23);        
CREATE CACHED TABLE "PUBLIC"."TBL_MODULO"(
    "ID" INTEGER GENERATED BY DEFAULT AS IDENTITY(START WITH 1) DEFAULT ON NULL NOT NULL,
    "DESCRICAO" CHARACTER VARYING(255),
    "NAME" CHARACTER VARYING(255) NOT NULL,
    "ENV_FK" INTEGER NOT NULL
);
ALTER TABLE "PUBLIC"."TBL_MODULO" ADD CONSTRAINT "PUBLIC"."CONSTRAINT_61" PRIMARY KEY("ID");  
-- 0 +/- SELECT COUNT(*) FROM PUBLIC.TBL_MODULO;              
CREATE CACHED TABLE "PUBLIC"."TBL_ORGANIZATION"(
    "ID" INTEGER GENERATED BY DEFAULT AS IDENTITY(START WITH 4) DEFAULT ON NULL NOT NULL,
    "CODE" CHARACTER VARYING(255) NOT NULL,
    "NAME" CHARACTER VARYING(255) NOT NULL,
    "PLSQL_CODE" CHARACTER VARYING(255),
    "STATUS" INTEGER NOT NULL,
    "ENV_FK" INTEGER NOT NULL,
    "SELF_FK" INTEGER,
    "USER_CREATED_FK" INTEGER
);    
ALTER TABLE "PUBLIC"."TBL_ORGANIZATION" ADD CONSTRAINT "PUBLIC"."CONSTRAINT_8" PRIMARY KEY("ID");             
-- 3 +/- SELECT COUNT(*) FROM PUBLIC.TBL_ORGANIZATION;        
INSERT INTO "PUBLIC"."TBL_ORGANIZATION" VALUES
(1, '01.03', 'IGRP', NULL, 1, 1, NULL, 1),
(2, 'org.tutorial', 'Tutorial', NULL, 1, 2, NULL, 1),
(3, 'org.developer', 'Developers', NULL, 1, 3, NULL, 1);   
CREATE CACHED TABLE "PUBLIC"."TBL_PROFILE"(
    "ID" INTEGER GENERATED BY DEFAULT AS IDENTITY(START WITH 60) DEFAULT ON NULL NOT NULL,
    "TYPE" CHARACTER VARYING(255) NOT NULL,
    "TYPE_FK" INTEGER NOT NULL,
    "ORG_FK" INTEGER NOT NULL,
    "PROF_TYPE_FK" INTEGER NOT NULL,
    "USER_FK" INTEGER
);        
ALTER TABLE "PUBLIC"."TBL_PROFILE" ADD CONSTRAINT "PUBLIC"."CONSTRAINT_7F" PRIMARY KEY("ID"); 
-- 59 +/- SELECT COUNT(*) FROM PUBLIC.TBL_PROFILE;            
INSERT INTO "PUBLIC"."TBL_PROFILE" VALUES
(1, 'ENV', 1, 1, 2, 2),
(2, 'PROF', 2, 1, 2, 2),
(3, 'ENV', 2, 2, 3, 2),
(4, 'PROF', 3, 2, 3, 2),
(5, 'ENV', 3, 3, 4, 2),
(6, 'PROF', 4, 3, 4, 2),
(7, 'ENV', 1, 1, 2, 1),
(8, 'PROF', 2, 1, 2, 1),
(9, 'ENV', 2, 2, 3, 1),
(10, 'PROF', 3, 2, 3, 1),
(11, 'ENV', 3, 3, 4, 1),
(12, 'PROF', 4, 3, 4, 1),
(13, 'MEN', 5, 1, 2, 1),
(14, 'MEN', 5, 1, 1, 1),
(15, 'MEN', 5, 3, 1, 1),
(16, 'MEN', 6, 3, 1, 1),
(17, 'MEN', 7, 3, 1, 1),
(18, 'MEN', 8, 1, 1, 1),
(19, 'MEN', 9, 1, 1, 1),
(20, 'MEN', 10, 1, 1, 1),
(21, 'MEN', 11, 1, 1, 1),
(22, 'MEN', 12, 1, 1, 1),
(23, 'MEN', 16, 1, 1, 1),
(24, 'MEN', 8, 3, 1, 1),
(25, 'MEN', 9, 3, 1, 1),
(26, 'MEN', 10, 3, 1, 1),
(27, 'MEN', 13, 3, 1, 1),
(28, 'MEN', 14, 3, 1, 1),
(29, 'MEN', 15, 1, 1, 1),
(30, 'MEN', 15, 3, 1, 1),
(31, 'MEN', 5, 3, 4, 1),
(32, 'MEN', 6, 3, 4, 1),
(33, 'MEN', 7, 3, 4, 1),
(34, 'MEN', 8, 1, 2, 1),
(35, 'MEN', 9, 1, 2, 1),
(36, 'MEN', 10, 1, 2, 1),
(37, 'MEN', 11, 1, 2, 1),
(38, 'MEN', 12, 1, 2, 1),
(39, 'MEN', 15, 1, 2, 1),
(40, 'MEN', 16, 1, 2, 1),
(41, 'MEN', 8, 3, 4, 1),
(42, 'MEN', 9, 3, 4, 1),
(43, 'MEN', 10, 3, 4, 1),
(44, 'MEN', 13, 3, 4, 1),
(45, 'MEN', 14, 3, 4, 1),
(46, 'MEN', 15, 3, 4, 1),
(47, 'MEN', 17, 3, 1, 1),
(48, 'MEN', 17, 1, 2, 1),
(49, 'MEN', 17, 3, 4, 1),
(50, 'MEN', 18, 3, 1, 1),
(51, 'MEN', 18, 3, 4, 1),
(52, 'MEN', 19, 1, 1, 1),
(53, 'MEN', 19, 1, 2, 1),
(54, 'MEN', 20, 3, 1, 1),
(55, 'MEN', 20, 3, 4, 1),
(56, 'MEN', 21, 3, 1, 1),
(57, 'MEN', 21, 3, 4, 1),
(58, 'MEN', 22, 3, 1, 1),
(59, 'MEN', 22, 3, 4, 1);           
CREATE CACHED TABLE "PUBLIC"."TBL_PROFILE_TYPE"(
    "ID" INTEGER GENERATED BY DEFAULT AS IDENTITY(START WITH 5) DEFAULT ON NULL NOT NULL,
    "CODE" CHARACTER VARYING(255) NOT NULL,
    "DESCR" CHARACTER VARYING(255) NOT NULL,
    "PLSQL_CODE" CHARACTER VARYING(255),
    "STATUS" INTEGER NOT NULL,
    "ENV_FK" INTEGER NOT NULL,
    "FIRSTPAGE" INTEGER,
    "ORG_FK" INTEGER,
    "SELF_FK" INTEGER
);  
ALTER TABLE "PUBLIC"."TBL_PROFILE_TYPE" ADD CONSTRAINT "PUBLIC"."CONSTRAINT_9" PRIMARY KEY("ID");             
-- 4 +/- SELECT COUNT(*) FROM PUBLIC.TBL_PROFILE_TYPE;        
INSERT INTO "PUBLIC"."TBL_PROFILE_TYPE" VALUES
(1, 'ALL', 'ALL PROFILE', NULL, 1, 1, NULL, NULL, NULL),
(2, 'ADMIN', 'Administrador', NULL, 1, 1, NULL, 1, NULL),
(3, 'perfil.tutorial', 'Tutorial', NULL, 1, 2, NULL, 2, NULL),
(4, 'perfil.developer', 'Developer', NULL, 1, 3, NULL, 3, NULL);         
CREATE CACHED TABLE "PUBLIC"."TBL_REP_INSTANCE"(
    "ID" INTEGER GENERATED BY DEFAULT AS IDENTITY(START WITH 1) DEFAULT ON NULL NOT NULL,
    "CONTRA_PROVA" CHARACTER VARYING(255) NOT NULL,
    "DT_CREATED" DATE NOT NULL,
    "REF_FK" INTEGER NOT NULL,
    "REFERENCE" CHARACTER VARYING(255),
    "UPDATEDATETIME" TIMESTAMP,
    "ENV_FK" INTEGER NOT NULL,
    "REP_TEMPLATE_FK" INTEGER,
    "USER_FK" INTEGER,
    "XML_CONTENT_FK" INTEGER NOT NULL,
    "XSL_CONTENT_FK" INTEGER NOT NULL
);        
ALTER TABLE "PUBLIC"."TBL_REP_INSTANCE" ADD CONSTRAINT "PUBLIC"."CONSTRAINT_3" PRIMARY KEY("ID");             
-- 0 +/- SELECT COUNT(*) FROM PUBLIC.TBL_REP_INSTANCE;        
CREATE CACHED TABLE "PUBLIC"."TBL_REP_TEMPLATE"(
    "ID" INTEGER GENERATED BY DEFAULT AS IDENTITY(START WITH 1) DEFAULT ON NULL NOT NULL,
    "CODE" CHARACTER VARYING(255),
    "DT_CREATED" DATE,
    "DT_UPDATED" DATE,
    "NAME" CHARACTER VARYING(255) NOT NULL,
    "REPORT_IDENTIFY" CHARACTER VARYING(255),
    "STATUS" INTEGER NOT NULL,
    "ENV_FK" INTEGER NOT NULL,
    "USER_CREATED_FK" INTEGER NOT NULL,
    "USER_UPDATED_FK" INTEGER NOT NULL,
    "XML_CONTENT_FK" INTEGER NOT NULL,
    "XSL_CONTENT_FK" INTEGER NOT NULL
);              
ALTER TABLE "PUBLIC"."TBL_REP_TEMPLATE" ADD CONSTRAINT "PUBLIC"."CONSTRAINT_93" PRIMARY KEY("ID");            
-- 0 +/- SELECT COUNT(*) FROM PUBLIC.TBL_REP_TEMPLATE;        
CREATE CACHED TABLE "PUBLIC"."TBL_REP_TEMPLATE_PARAM"(
    "ID" INTEGER GENERATED BY DEFAULT AS IDENTITY(START WITH 1) DEFAULT ON NULL NOT NULL,
    "PARAMETER" CHARACTER VARYING(255) NOT NULL,
    "REP_TEMPLATE_FK" INTEGER NOT NULL
);               
ALTER TABLE "PUBLIC"."TBL_REP_TEMPLATE_PARAM" ADD CONSTRAINT "PUBLIC"."CONSTRAINT_6B" PRIMARY KEY("ID");      
-- 0 +/- SELECT COUNT(*) FROM PUBLIC.TBL_REP_TEMPLATE_PARAM;  
CREATE CACHED TABLE "PUBLIC"."TBL_REP_TEMPLATE_SOURCE"(
    "ID" INTEGER GENERATED BY DEFAULT AS IDENTITY(START WITH 1) DEFAULT ON NULL NOT NULL,
    "REP_SOURCE_FK" INTEGER NOT NULL,
    "REP_TEMPLATE_FK" INTEGER NOT NULL
);         
ALTER TABLE "PUBLIC"."TBL_REP_TEMPLATE_SOURCE" ADD CONSTRAINT "PUBLIC"."CONSTRAINT_1" PRIMARY KEY("ID");      
-- 0 +/- SELECT COUNT(*) FROM PUBLIC.TBL_REP_TEMPLATE_SOURCE; 
CREATE CACHED TABLE "PUBLIC"."TBL_REP_TEMPLATE_SOURCE_PARAM"(
    "ID" INTEGER GENERATED BY DEFAULT AS IDENTITY(START WITH 1) DEFAULT ON NULL NOT NULL,
    "PARAMETER" CHARACTER VARYING(70) NOT NULL,
    "PARAMETER_TYPE" CHARACTER VARYING(50) NOT NULL,
    "REP_TEMPLATE_SOURCE_FK" INTEGER NOT NULL
);            
ALTER TABLE "PUBLIC"."TBL_REP_TEMPLATE_SOURCE_PARAM" ADD CONSTRAINT "PUBLIC"."CONSTRAINT_CD" PRIMARY KEY("ID");               
-- 0 +/- SELECT COUNT(*) FROM PUBLIC.TBL_REP_TEMPLATE_SOURCE_PARAM;           
CREATE CACHED TABLE "PUBLIC"."TBL_TASK_ACCESS"(
    "ID" INTEGER GENERATED BY DEFAULT AS IDENTITY(START WITH 1) DEFAULT ON NULL NOT NULL,
    "PROCESSNAME" CHARACTER VARYING(150),
    "TASKDESCRIPTION" CHARACTER VARYING(255),
    "TASKNAME" CHARACTER VARYING(100),
    "USER_FK" INTEGER,
    "ORG_FK" INTEGER NOT NULL,
    "PROF_FK" INTEGER
);               
ALTER TABLE "PUBLIC"."TBL_TASK_ACCESS" ADD CONSTRAINT "PUBLIC"."CONSTRAINT_D8" PRIMARY KEY("ID");             
-- 0 +/- SELECT COUNT(*) FROM PUBLIC.TBL_TASK_ACCESS;         
CREATE CACHED TABLE "PUBLIC"."TBL_TASK_COMPONENT"(
    "ID" INTEGER GENERATED BY DEFAULT AS IDENTITY(START WITH 1) DEFAULT ON NULL NOT NULL,
    "CODIGO" CHARACTER VARYING(255) NOT NULL,
    "ORDEM" SMALLINT NOT NULL,
    "PROCESSID" CHARACTER VARYING(255) NOT NULL,
    "TASKID" CHARACTER VARYING(255) NOT NULL,
    "TITLE" CHARACTER VARYING(255),
    "ACTION_FK" INTEGER NOT NULL
);      
ALTER TABLE "PUBLIC"."TBL_TASK_COMPONENT" ADD CONSTRAINT "PUBLIC"."CONSTRAINT_5E" PRIMARY KEY("ID");          
-- 0 +/- SELECT COUNT(*) FROM PUBLIC.TBL_TASK_COMPONENT;      
CREATE CACHED TABLE "PUBLIC"."TBL_TASK_FILE"(
    "ID" INTEGER GENERATED BY DEFAULT AS IDENTITY(START WITH 1) DEFAULT ON NULL NOT NULL,
    "ESTADO" CHARACTER VARYING(255),
    "TASK_ID" CHARACTER VARYING(20) NOT NULL,
    "UUID" CHARACTER VARYING(255),
    "CLOB_FK" INTEGER NOT NULL,
    "TIPO_DOCUMENTO_ETAPA_FK" INTEGER NOT NULL
);        
ALTER TABLE "PUBLIC"."TBL_TASK_FILE" ADD CONSTRAINT "PUBLIC"."CONSTRAINT_CC" PRIMARY KEY("ID");               
-- 0 +/- SELECT COUNT(*) FROM PUBLIC.TBL_TASK_FILE;           
CREATE CACHED TABLE "PUBLIC"."TBL_TASK_UNASSIGNED"(
    "ID" INTEGER GENERATED BY DEFAULT AS IDENTITY(START WITH 1) DEFAULT ON NULL NOT NULL,
    "NOASSUMED" BOOLEAN NOT NULL,
    "PROCESSKEY" CHARACTER VARYING(150) NOT NULL,
    "TASKID" CHARACTER VARYING(50) NOT NULL,
    "TASKKEY" CHARACTER VARYING(150) NOT NULL,
    "USER_FK" INTEGER NOT NULL
);        
ALTER TABLE "PUBLIC"."TBL_TASK_UNASSIGNED" ADD CONSTRAINT "PUBLIC"."CONSTRAINT_DE" PRIMARY KEY("ID");         
-- 0 +/- SELECT COUNT(*) FROM PUBLIC.TBL_TASK_UNASSIGNED;     
CREATE CACHED TABLE "PUBLIC"."TBL_TEMP_FILE"(
    "UUID" CHARACTER VARYING(255) NOT NULL,
    "CONTENT" BINARY(255) NOT NULL,
    "DATE_CREATED" DATE,
    "MIME_TYPE" CHARACTER VARYING(255),
    "NAME" CHARACTER VARYING(255),
    "SIZE" BIGINT NOT NULL
);        
ALTER TABLE "PUBLIC"."TBL_TEMP_FILE" ADD CONSTRAINT "PUBLIC"."CONSTRAINT_37" PRIMARY KEY("UUID");             
-- 0 +/- SELECT COUNT(*) FROM PUBLIC.TBL_TEMP_FILE;           
CREATE CACHED TABLE "PUBLIC"."TBL_TIPO_DOCUMENTO"(
    "ID" INTEGER GENERATED BY DEFAULT AS IDENTITY(START WITH 1) DEFAULT ON NULL NOT NULL,
    "CODIGO" CHARACTER VARYING(50),
    "DESCRICAO" CHARACTER VARYING(500),
    "NOME" CHARACTER VARYING(100) NOT NULL,
    "STATUS" INTEGER NOT NULL,
    "ENV_FK" INTEGER NOT NULL
);   
ALTER TABLE "PUBLIC"."TBL_TIPO_DOCUMENTO" ADD CONSTRAINT "PUBLIC"."CONSTRAINT_9B" PRIMARY KEY("ID");          
-- 0 +/- SELECT COUNT(*) FROM PUBLIC.TBL_TIPO_DOCUMENTO;      
CREATE CACHED TABLE "PUBLIC"."TBL_TIPO_DOCUMENTO_ETAPA"(
    "ID" INTEGER GENERATED BY DEFAULT AS IDENTITY(START WITH 1) DEFAULT ON NULL NOT NULL,
    "PROCESSID" CHARACTER VARYING(100) NOT NULL,
    "REQUIRED" INTEGER NOT NULL,
    "STATUS" INTEGER NOT NULL,
    "TASKID" CHARACTER VARYING(100) NOT NULL,
    "TIPO" CHARACTER VARYING(4) NOT NULL,
    "REPORT_FK" INTEGER,
    "TIPO_DOCUMENTO_FK" INTEGER
);              
ALTER TABLE "PUBLIC"."TBL_TIPO_DOCUMENTO_ETAPA" ADD CONSTRAINT "PUBLIC"."CONSTRAINT_84" PRIMARY KEY("ID");    
-- 0 +/- SELECT COUNT(*) FROM PUBLIC.TBL_TIPO_DOCUMENTO_ETAPA;
CREATE CACHED TABLE "PUBLIC"."TBL_TRANSACTION"(
    "ID" INTEGER GENERATED BY DEFAULT AS IDENTITY(START WITH 1) DEFAULT ON NULL NOT NULL,
    "CODE" CHARACTER VARYING(255) NOT NULL,
    "DESCR" CHARACTER VARYING(255) NOT NULL,
    "EXTERNAL" INTEGER,
    "STATUS" INTEGER NOT NULL,
    "ENV_FK" INTEGER NOT NULL
);             
ALTER TABLE "PUBLIC"."TBL_TRANSACTION" ADD CONSTRAINT "PUBLIC"."CONSTRAINT_60" PRIMARY KEY("ID");             
-- 0 +/- SELECT COUNT(*) FROM PUBLIC.TBL_TRANSACTION;         
CREATE CACHED TABLE "PUBLIC"."TBL_USER"(
    "ID" INTEGER GENERATED BY DEFAULT AS IDENTITY(START WITH 4) DEFAULT ON NULL NOT NULL,
    "ACTIVATION_KEY" CHARACTER VARYING(255) NOT NULL,
    "AUTH_KEY" CHARACTER VARYING(255),
    "CREATED_AT" BIGINT NOT NULL,
    "EMAIL" CHARACTER VARYING(255),
    "IS_AUTHENTICATED" INTEGER,
    "MOBILE" CHARACTER VARYING(255),
    "NAME" CHARACTER VARYING(255),
    "OIDC_ID_TOKEN" CHARACTER LARGE OBJECT,
    "OIDC_STATE" CHARACTER VARYING(255),
    "PASS_HASH" CHARACTER VARYING(255),
    "PASSWORD_RESET_TOKEN" CHARACTER VARYING(255),
    "PHONE" CHARACTER VARYING(255),
    "PHOTO_ID" CHARACTER VARYING(255),
    "REFRESH_TOKEN" CHARACTER VARYING(255),
    "REMARKS" CHARACTER VARYING(255),
    "SIGNATURE_ID" CHARACTER VARYING(255),
    "STATUS" INTEGER NOT NULL,
    "UPDATED_AT" BIGINT NOT NULL,
    "USERPROFILE" CHARACTER VARYING(255),
    "USER_NAME" CHARACTER VARYING(255),
    "VALID_UNTIL" CHARACTER VARYING(255)
);   
ALTER TABLE "PUBLIC"."TBL_USER" ADD CONSTRAINT "PUBLIC"."CONSTRAINT_405" PRIMARY KEY("ID");   
-- 3 +/- SELECT COUNT(*) FROM PUBLIC.TBL_USER;
INSERT INTO "PUBLIC"."TBL_USER" VALUES
(1, '123456789', '123456789', 2017, 'igrpweb@nosi.cv', NULL, NULL, 'IGRP SysAdmin', NULL, NULL, 'dc4659bfb1dbb064106f5685aa87a41550402178b0cc4c43a52f82848bb78b34', NULL, NULL, NULL, NULL, NULL, NULL, 1, 2017, 'ADMIN', 'igrpweb@nosi.cv', NULL),
(2, '123456789', '123456', 2017, 'demo@nosi.cv', 1, NULL, 'Nositeste', NULL, NULL, '60b1df41fa82696abea1deb198667eb7c4a60521dd471559a8c17efde8528913', NULL, NULL, NULL, NULL, NULL, NULL, 1, 2017, 'ADMIN', 'demo@nosi.cv', NULL),
(3, '123456789', '123456', 12345, NULL, NULL, NULL, NULL, NULL, NULL, 'Pa$$w0rd', NULL, NULL, NULL, NULL, NULL, NULL, 1, 133, NULL, 'root', NULL);          
CREATE FORCE VIEW "PUBLIC"."GLB_MV_ALL_MENUS"("ID", "DESCR", "DESCR_MENU", "SELF_FK", "ENV_FK", "ACTION_FK", "ORDERBY") AS
SELECT
    "A"."ID",
    "A"."DESCR" AS "DESCR",
    "A"."DESCR" AS "DESCR_MENU",
    "A"."SELF_FK",
    "A"."ENV_FK",
    "A"."ACTION_FK",
    "A"."ORDERBY"
FROM "PUBLIC"."TBL_MENU" "A"
INNER JOIN "PUBLIC"."TBL_MENU" "B"
    ON 1=1
WHERE ("A"."SELF_FK" IS NOT NULL)
    AND ("B"."ID" = "A"."SELF_FK");        
CREATE FORCE VIEW "PUBLIC"."GLB_MV_MENU"("ID", "DESCR", "SELF_FK", "ENV_FK", "ACTION_FK", "ORDERBY", "STATUS", "FLG_BASE", "TARGET") AS
SELECT
    "ID",
    "DESCR",
    "SELF_FK",
    "ENV_FK",
    "ACTION_FK",
    "ORDERBY",
    "STATUS",
    "FLG_BASE",
    "TARGET"
FROM "PUBLIC"."TBL_MENU";            
CREATE FORCE VIEW "PUBLIC"."GLB_V_MENU"("ID", "DESCR", "DESCR_MENU", "SELF_FK", "ENV_FK", "ACTION_FK", "ORDERBY") AS
SELECT
    "A"."ID",
    "B"."DESCR" || ' - ' || "A"."DESCR" AS "DESCR",
    "A"."DESCR" AS "DESCR_MENU",
    "A"."SELF_FK",
    "A"."ENV_FK",
    "A"."ACTION_FK",
    "A"."ORDERBY"
FROM "PUBLIC"."GLB_MV_MENU" "A"
INNER JOIN "PUBLIC"."GLB_MV_MENU" "B"
    ON 1=1
WHERE ("A"."SELF_FK" IS NOT NULL)
    AND ("B"."ID" = "A"."SELF_FK");
CREATE FORCE VIEW "PUBLIC"."GLB_V_ORG_MENU"("ID", "DESCR", "ORDERBY", "ENV_FK", "SELF_FK", "PROF_TYPE_FK", "USER_FK", "PROF_CODE", "PROF_NAME", "ORG_FK", "FLG_BASE") AS
SELECT
    "A"."ID",
    "E"."DESCR" || ' - ' || "A"."DESCR" AS "DESCR",
    "A"."ORDERBY",
    "A"."ENV_FK",
    "A"."SELF_FK",
    "B"."PROF_TYPE_FK",
    "B"."USER_FK",
    'ALL' AS "PROF_CODE",
    'ALL PROFILE' AS "PROF_NAME",
    "B"."ORG_FK",
    "A"."FLG_BASE"
FROM "PUBLIC"."TBL_MENU" "A"
INNER JOIN "PUBLIC"."TBL_MENU" "E"
    ON 1=1
INNER JOIN "PUBLIC"."TBL_PROFILE" "B"
    ON 1=1
WHERE ("B"."TYPE" = 'MEN')
    AND ("B"."PROF_TYPE_FK" = 0)
    AND ("A"."SELF_FK" IS NOT NULL)
    AND ("A"."ID" = "B"."TYPE_FK")
    AND ("E"."ID" = "A"."SELF_FK");
CREATE FORCE VIEW "PUBLIC"."GLB_MV_PROFILE"("PROF_TYPE_FK", "USER_FK", "TYPE", "TYPE_FK", "ORG_FK") AS
SELECT
    "PROF_TYPE_FK",
    "USER_FK",
    "TYPE",
    "TYPE_FK",
    "ORG_FK"
FROM "PUBLIC"."TBL_PROFILE";  
CREATE FORCE VIEW "PUBLIC"."GLB_MV_PROFILE_TYPE"("ID", "DESCR", "CODE", "ENV_FK", "SELF_FK", "STATUS", "ORG_FK") AS
SELECT
    "ID",
    "DESCR",
    "CODE",
    "ENV_FK",
    "SELF_FK",
    "STATUS",
    "ORG_FK"
FROM "PUBLIC"."TBL_PROFILE_TYPE";              
CREATE FORCE VIEW "PUBLIC"."GLB_V_PROFILE"("ORG_FK", "PROF_TYPE_FK", "USER_FK", "TYPE", "TYPE_FK", "PROF_CODE", "PROF_NAME", "PROF_NAME_DESC", "ENV_FK", "SELF_FK") AS
SELECT
    "B"."ORG_FK",
    "B"."PROF_TYPE_FK",
    "B"."USER_FK",
    "B"."TYPE",
    "B"."TYPE_FK",
    "D"."CODE" AS "PROF_CODE",
    "D"."DESCR" AS "PROF_NAME",
    "D"."CODE" || ' - ' || "D"."DESCR" AS "PROF_NAME_DESC",
    "D"."ENV_FK",
    "D"."SELF_FK"
FROM "PUBLIC"."GLB_MV_PROFILE" "B"
INNER JOIN "PUBLIC"."GLB_MV_PROFILE_TYPE" "D"
    ON 1=1
WHERE "D"."ID" = "B"."PROF_TYPE_FK";  
CREATE FORCE VIEW "PUBLIC"."GLB_V_PROFILE_MENU"("ID", "DESCR", "DESCR_MENU", "ORDERBY", "ENV_FK", "SELF_FK", "ACTION_FK", "PROF_TYPE_FK", "USER_FK", "PROF_CODE", "PROF_NAME", "ORG_FK", "STATUS", "TARGET", "ENV_FK_PROF_TYPE", "FLG_BASE") AS
SELECT
    "A"."ID",
    "E"."DESCR" AS "DESCR",
    "A"."DESCR" AS "DESCR_MENU",
    "A"."ORDERBY",
    "A"."ENV_FK",
    "A"."SELF_FK",
    "A"."ACTION_FK",
    "B"."PROF_TYPE_FK",
    "B"."USER_FK",
    "D"."CODE" AS "PROF_CODE",
    "D"."DESCR" AS "PROF_NAME",
    "B"."ORG_FK",
    "A"."STATUS",
    "A"."TARGET",
    "D"."ENV_FK" AS "ENV_FK_PROF_TYPE",
    "E"."FLG_BASE"
FROM "PUBLIC"."GLB_MV_MENU" "A"
INNER JOIN "PUBLIC"."GLB_MV_MENU" "E"
    ON 1=1
INNER JOIN "PUBLIC"."GLB_MV_PROFILE" "B"
    ON 1=1
INNER JOIN "PUBLIC"."GLB_MV_PROFILE_TYPE" "D"
    ON 1=1
WHERE ("B"."TYPE" = 'MEN')
    AND ("A"."SELF_FK" IS NOT NULL)
    AND ("A"."ID" = "B"."TYPE_FK")
    AND ("D"."ID" = "B"."PROF_TYPE_FK")
    AND ("E"."ID" = "A"."SELF_FK");            
CREATE FORCE VIEW "PUBLIC"."GLB_V_USER_MENU"("ID", "DESCR", "ORDERBY", "ENV_FK", "SELF_FK", "PROF_TYPE_FK", "USER_FK", "PROF_CODE", "PROF_NAME", "ORG_FK") AS
SELECT
    "ID",
    "DESCR",
    "ORDERBY",
    "ENV_FK",
    "SELF_FK",
    "PROF_TYPE_FK",
    "USER_FK",
    "PROF_CODE",
    "PROF_NAME",
    "ORG_FK"
FROM "PUBLIC"."GLB_V_PROFILE_MENU"
WHERE "USER_FK" <> 0;               
CREATE FORCE VIEW "PUBLIC"."GLB_V_PROF_MENU"("ID", "DESCR", "DESCR_MENU", "ORDERBY", "ENV_FK", "SELF_FK", "ACTION_FK", "PROF_TYPE_FK", "USER_FK", "PROF_CODE", "PROF_NAME", "ORG_FK", "STATUS", "TARGET", "ENV_FK_PROF_TYPE", "FLG_BASE") AS
SELECT
    "ID",
    "DESCR",
    "DESCR_MENU",
    "ORDERBY",
    "ENV_FK",
    "SELF_FK",
    "ACTION_FK",
    "PROF_TYPE_FK",
    "USER_FK",
    "PROF_CODE",
    "PROF_NAME",
    "ORG_FK",
    "STATUS",
    "TARGET",
    "ENV_FK_PROF_TYPE",
    "FLG_BASE"
FROM "PUBLIC"."GLB_V_PROFILE_MENU"
WHERE ("PROF_TYPE_FK" <> 0)
    AND ("USER_FK" = 0);   
CREATE FORCE VIEW "PUBLIC"."GLB_MV_TRANSACTION"("ID", "CODE", "DESCR", "ENV_FK", "STATUS") AS
SELECT
    "ID",
    "CODE",
    "DESCR",
    "ENV_FK",
    "STATUS"
FROM "PUBLIC"."TBL_TRANSACTION";    
CREATE FORCE VIEW "PUBLIC"."GLB_V_PROFILE_TRANS"("ID", "CODE", "DESCR", "ENV_FK", "PROF_TYPE_FK", "USER_FK", "PROF_CODE", "PROF_NAME", "ORG_FK") AS
SELECT
    "A"."ID",
    "A"."CODE",
    "A"."DESCR",
    "A"."ENV_FK",
    "B"."PROF_TYPE_FK",
    "B"."USER_FK",
    "B"."PROF_CODE",
    "B"."PROF_NAME",
    "B"."ORG_FK"
FROM "PUBLIC"."TBL_TRANSACTION" "A"
INNER JOIN "PUBLIC"."GLB_V_PROFILE" "B"
    ON 1=1
WHERE ("B"."TYPE" = 'TRANS')
    AND ("A"."ID" = "B"."TYPE_FK");      
CREATE FORCE VIEW "PUBLIC"."GLB_V_PROF_TRANS"("ID", "CODE", "DESCR", "ENV_FK", "PROF_TYPE_FK", "USER_FK", "PROF_CODE", "PROF_NAME", "ORG_FK") AS
SELECT
    "ID",
    "CODE",
    "DESCR",
    "ENV_FK",
    "PROF_TYPE_FK",
    "USER_FK",
    "PROF_CODE",
    "PROF_NAME",
    "ORG_FK"
FROM "PUBLIC"."GLB_V_PROFILE_TRANS"
WHERE ("PROF_TYPE_FK" <> 0)
    AND ("USER_FK" = 0);              
CREATE FORCE VIEW "PUBLIC"."GLB_V_ORG_TRANS"("ID", "CODE", "DESCR", "ENV_FK", "PROF_TYPE_FK", "USER_FK", "PROF_CODE", "PROF_NAME", "ORG_FK") AS
SELECT
    "ID",
    "CODE",
    "DESCR",
    "ENV_FK",
    "PROF_TYPE_FK",
    "USER_FK",
    "PROF_CODE",
    "PROF_NAME",
    "ORG_FK"
FROM "PUBLIC"."GLB_V_PROFILE_TRANS"
WHERE "PROF_TYPE_FK" = 0;           
CREATE FORCE VIEW "PUBLIC"."GLB_V_USER_TRANS"("ID", "CODE", "DESCR", "ENV_FK", "PROF_TYPE_FK", "USER_FK", "PROF_CODE", "PROF_NAME", "ORG_FK") AS
SELECT
    "ID",
    "CODE",
    "DESCR",
    "ENV_FK",
    "PROF_TYPE_FK",
    "USER_FK",
    "PROF_CODE",
    "PROF_NAME",
    "ORG_FK"
FROM "PUBLIC"."GLB_V_PROFILE_TRANS"
WHERE "USER_FK" <> 0;              
ALTER TABLE "PUBLIC"."TBL_PROFILE" ADD CONSTRAINT "PUBLIC"."PROFILE_UNIQUE_FK" UNIQUE("TYPE", "TYPE_FK", "USER_FK", "ORG_FK", "PROF_TYPE_FK");
ALTER TABLE "PUBLIC"."TBL_ORGANIZATION" ADD CONSTRAINT "PUBLIC"."UK_2NGUYAYAV3WM6YJ1J093RGBEU" UNIQUE("CODE");
ALTER TABLE "PUBLIC"."TBL_CONFIG" ADD CONSTRAINT "PUBLIC"."UK_12MHJ0S9YHG2VYN29MHL8J8UY" UNIQUE("NAME");      
ALTER TABLE "PUBLIC"."TBL_USER" ADD CONSTRAINT "PUBLIC"."UK_6JR81L5QQPXJP72FGI23UBQC9" UNIQUE("USER_NAME");   
ALTER TABLE "PUBLIC"."TBL_USER" ADD CONSTRAINT "PUBLIC"."UK_NPN1WF1YU1G5RJOHBEK375PP1" UNIQUE("EMAIL");       
ALTER TABLE "PUBLIC"."TBL_ENV" ADD CONSTRAINT "PUBLIC"."UK_6M6WU64XN2K5PU1JT30H6R13Y" UNIQUE("DAD");          
ALTER TABLE "PUBLIC"."TBL_PROFILE_TYPE" ADD CONSTRAINT "PUBLIC"."UK_PSNLUQOOFBS9NXJW813KTE4D1" UNIQUE("CODE");
ALTER TABLE "PUBLIC"."TBL_DOMAIN" ADD CONSTRAINT "PUBLIC"."DOMAIN_ENV_FK" FOREIGN KEY("ENV_FK") REFERENCES "PUBLIC"."TBL_ENV"("ID") NOCHECK;  
ALTER TABLE "PUBLIC"."TBL_MENU" ADD CONSTRAINT "PUBLIC"."MENU_ENV_FK" FOREIGN KEY("ENV_FK") REFERENCES "PUBLIC"."TBL_ENV"("ID") NOCHECK;      
ALTER TABLE "PUBLIC"."TBL_ACTIVITY_EXECUTE" ADD CONSTRAINT "PUBLIC"."USER_ACTIVITE_EXECUTE_FK" FOREIGN KEY("USER_FK") REFERENCES "PUBLIC"."TBL_USER"("ID") NOCHECK;           
ALTER TABLE "PUBLIC"."TBL_CLOB" ADD CONSTRAINT "PUBLIC"."CLOB_USER_CREATED_FK" FOREIGN KEY("USER_CREATED_FK") REFERENCES "PUBLIC"."TBL_USER"("ID") NOCHECK;   
ALTER TABLE "PUBLIC"."TBL_TIPO_DOCUMENTO_ETAPA" ADD CONSTRAINT "PUBLIC"."TIPO_DOCUEMNTO_ETAPA_TIPO_DOCUMENTO_FK" FOREIGN KEY("TIPO_DOCUMENTO_FK") REFERENCES "PUBLIC"."TBL_TIPO_DOCUMENTO"("ID") NOCHECK;     
ALTER TABLE "PUBLIC"."TBL_ENV" ADD CONSTRAINT "PUBLIC"."ENV_ACTION_FK" FOREIGN KEY("ACTION_FK") REFERENCES "PUBLIC"."TBL_ACTION"("ID") NOCHECK;               
ALTER TABLE "PUBLIC"."TBL_PROFILE" ADD CONSTRAINT "PUBLIC"."PROFILE_PROF_TYPE_FK" FOREIGN KEY("PROF_TYPE_FK") REFERENCES "PUBLIC"."TBL_PROFILE_TYPE"("ID") NOCHECK;           
ALTER TABLE "PUBLIC"."TBL_ORGANIZATION" ADD CONSTRAINT "PUBLIC"."ORGANIZATION_ENV_FK" FOREIGN KEY("ENV_FK") REFERENCES "PUBLIC"."TBL_ENV"("ID") NOCHECK;      
ALTER TABLE "PUBLIC"."TBL_HISTORIC" ADD CONSTRAINT "PUBLIC"."PAGE_FK" FOREIGN KEY("PAGE_FK") REFERENCES "PUBLIC"."TBL_ACTION"("ID") NOCHECK;  
ALTER TABLE "PUBLIC"."TBL_TASK_FILE" ADD CONSTRAINT "PUBLIC"."TASK_FILE_CLOB_FK" FOREIGN KEY("CLOB_FK") REFERENCES "PUBLIC"."TBL_CLOB"("ID") NOCHECK;         
ALTER TABLE "PUBLIC"."TBL_REP_TEMPLATE_SOURCE_PARAM" ADD CONSTRAINT "PUBLIC"."REP_TEMPLATE_SOURCE_PARAM_FK" FOREIGN KEY("REP_TEMPLATE_SOURCE_FK") REFERENCES "PUBLIC"."TBL_REP_TEMPLATE_SOURCE"("ID") NOCHECK;
ALTER TABLE "PUBLIC"."TBL_ACTIVITY_EXECUTE" ADD CONSTRAINT "PUBLIC"."ORG_ACTIVITE_EXECUTE_FK" FOREIGN KEY("ORG_FK") REFERENCES "PUBLIC"."TBL_ORGANIZATION"("ID") NOCHECK;     
ALTER TABLE "PUBLIC"."TBL_TASK_UNASSIGNED" ADD CONSTRAINT "PUBLIC"."USER_TASK_UNASSIGNED_FK" FOREIGN KEY("USER_FK") REFERENCES "PUBLIC"."TBL_USER"("ID") NOCHECK;             
ALTER TABLE "PUBLIC"."TBL_PROFILE_TYPE" ADD CONSTRAINT "PUBLIC"."PROFILE_TYPE_ACTION_FK" FOREIGN KEY("FIRSTPAGE") REFERENCES "PUBLIC"."TBL_ACTION"("ID") NOCHECK;             
ALTER TABLE "PUBLIC"."TBL_SESSION" ADD CONSTRAINT "PUBLIC"."SESSION_ENV_FK" FOREIGN KEY("ENV_FK") REFERENCES "PUBLIC"."TBL_ENV"("ID") NOCHECK;
ALTER TABLE "PUBLIC"."TBL_TIPO_DOCUMENTO_ETAPA" ADD CONSTRAINT "PUBLIC"."TIPO_DOCUEMNTO_ETAPA_REPORT_FK" FOREIGN KEY("REPORT_FK") REFERENCES "PUBLIC"."TBL_REP_TEMPLATE"("ID") NOCHECK;       
ALTER TABLE "PUBLIC"."TBL_ORGANIZATION" ADD CONSTRAINT "PUBLIC"."ORGANIZATION_SELF_FK" FOREIGN KEY("SELF_FK") REFERENCES "PUBLIC"."TBL_ORGANIZATION"("ID") NOCHECK;           
ALTER TABLE "PUBLIC"."TBL_PROFILE" ADD CONSTRAINT "PUBLIC"."PROFILE_USER_FK" FOREIGN KEY("USER_FK") REFERENCES "PUBLIC"."TBL_USER"("ID") NOCHECK;             
ALTER TABLE "PUBLIC"."TBL_REP_INSTANCE" ADD CONSTRAINT "PUBLIC"."REP_INSTANCE_ENV_FK" FOREIGN KEY("ENV_FK") REFERENCES "PUBLIC"."TBL_ENV"("ID") NOCHECK;      
ALTER TABLE "PUBLIC"."GLB_T_ACL" ADD CONSTRAINT "PUBLIC"."FKF2U26FJDYK9RR59WPSO7Y7L5S" FOREIGN KEY("ENV_FK") REFERENCES "PUBLIC"."TBL_ENV"("ID") NOCHECK;     
ALTER TABLE "PUBLIC"."TBL_TRANSACTION" ADD CONSTRAINT "PUBLIC"."TRANSACTION_SOURCE_ENV_FK" FOREIGN KEY("ENV_FK") REFERENCES "PUBLIC"."TBL_ENV"("ID") NOCHECK; 
ALTER TABLE "PUBLIC"."TBL_REP_TEMPLATE_PARAM" ADD CONSTRAINT "PUBLIC"."REP_TEMPLATE_PARAM_FK" FOREIGN KEY("REP_TEMPLATE_FK") REFERENCES "PUBLIC"."TBL_REP_TEMPLATE"("ID") NOCHECK;            
ALTER TABLE "PUBLIC"."TBL_ACTION" ADD CONSTRAINT "PUBLIC"."ACTION_ENV_FK" FOREIGN KEY("ENV_FK") REFERENCES "PUBLIC"."TBL_ENV"("ID") NOCHECK;  
ALTER TABLE "PUBLIC"."TBL_REP_TEMPLATE" ADD CONSTRAINT "PUBLIC"."REP_TEMPLATE_ENV_FK" FOREIGN KEY("ENV_FK") REFERENCES "PUBLIC"."TBL_ENV"("ID") NOCHECK;      
ALTER TABLE "PUBLIC"."TBL_PROFILE_TYPE" ADD CONSTRAINT "PUBLIC"."PROFILE_TYPE_SELF_FK" FOREIGN KEY("SELF_FK") REFERENCES "PUBLIC"."TBL_PROFILE_TYPE"("ID") NOCHECK;           
ALTER TABLE "PUBLIC"."TBL_SESSION" ADD CONSTRAINT "PUBLIC"."SESSION_USER_FK" FOREIGN KEY("USER_FK") REFERENCES "PUBLIC"."TBL_USER"("ID") NOCHECK;             
ALTER TABLE "PUBLIC"."TBL_SESSION" ADD CONSTRAINT "PUBLIC"."SESSION_PROF_TYPE_FK" FOREIGN KEY("PROF_TYPE_FK") REFERENCES "PUBLIC"."TBL_PROFILE_TYPE"("ID") NOCHECK;           
ALTER TABLE "PUBLIC"."TBL_ACTIVITY_EXECUTE" ADD CONSTRAINT "PUBLIC"."PROF_ACTIVITE_EXECUTE_FK" FOREIGN KEY("PROF_FK") REFERENCES "PUBLIC"."TBL_PROFILE_TYPE"("ID") NOCHECK;   
ALTER TABLE "PUBLIC"."TBL_REP_TEMPLATE" ADD CONSTRAINT "PUBLIC"."REP_TEMPLATE_USER_CREATED_FK" FOREIGN KEY("USER_CREATED_FK") REFERENCES "PUBLIC"."TBL_USER"("ID") NOCHECK;   
ALTER TABLE "PUBLIC"."TBL_MODULO" ADD CONSTRAINT "PUBLIC"."ENV_FK" FOREIGN KEY("ENV_FK") REFERENCES "PUBLIC"."TBL_ENV"("ID") NOCHECK;         
ALTER TABLE "PUBLIC"."TBL_CONFIG" ADD CONSTRAINT "PUBLIC"."CONFIG_FK" FOREIGN KEY("ENV_FK") REFERENCES "PUBLIC"."TBL_ENV"("ID") NOCHECK;      
ALTER TABLE "PUBLIC"."TBL_TASK_ACCESS" ADD CONSTRAINT "PUBLIC"."TASK_ACCESS_ORGANIZATION_FK" FOREIGN KEY("ORG_FK") REFERENCES "PUBLIC"."TBL_ORGANIZATION"("ID") NOCHECK;      
ALTER TABLE "PUBLIC"."TBL_MENU" ADD CONSTRAINT "PUBLIC"."MENU_ACTION_FK" FOREIGN KEY("ACTION_FK") REFERENCES "PUBLIC"."TBL_ACTION"("ID") NOCHECK;             
ALTER TABLE "PUBLIC"."TBL_PROFILE_TYPE" ADD CONSTRAINT "PUBLIC"."PROFILE_TYPE_ENV_FK" FOREIGN KEY("ENV_FK") REFERENCES "PUBLIC"."TBL_ENV"("ID") NOCHECK;      
ALTER TABLE "PUBLIC"."TBL_REP_TEMPLATE" ADD CONSTRAINT "PUBLIC"."REP_TEMPLATE_USER_UPDATED_FK" FOREIGN KEY("USER_UPDATED_FK") REFERENCES "PUBLIC"."TBL_USER"("ID") NOCHECK;   
ALTER TABLE "PUBLIC"."TBL_REP_TEMPLATE_SOURCE" ADD CONSTRAINT "PUBLIC"."REP_TEMPLATE_SOURCE_REP_TEMPLATE_FK" FOREIGN KEY("REP_TEMPLATE_FK") REFERENCES "PUBLIC"."TBL_REP_TEMPLATE"("ID") NOCHECK;             
ALTER TABLE "PUBLIC"."TBL_REP_INSTANCE" ADD CONSTRAINT "PUBLIC"."REP_INSTANCE_REP_TEMPLATE_FK" FOREIGN KEY("REP_TEMPLATE_FK") REFERENCES "PUBLIC"."TBL_REP_TEMPLATE"("ID") NOCHECK;           
ALTER TABLE "PUBLIC"."GLB_T_ACL" ADD CONSTRAINT "PUBLIC"."FK8EVEEJ9IA15D7RA4IHW8WYBSB" FOREIGN KEY("ENV_OWNER_FK") REFERENCES "PUBLIC"."TBL_ENV"("ID") NOCHECK;               
ALTER TABLE "PUBLIC"."TBL_ACTIVITY_EXECUTE" ADD CONSTRAINT "PUBLIC"."ENV_ACTIVITE_EXECUTE_FK" FOREIGN KEY("ENV_FK") REFERENCES "PUBLIC"."TBL_ENV"("ID") NOCHECK;              
ALTER TABLE "PUBLIC"."TBL_REP_INSTANCE" ADD CONSTRAINT "PUBLIC"."REP_INSTANCE_XSL_CONTENT_FK" FOREIGN KEY("XSL_CONTENT_FK") REFERENCES "PUBLIC"."TBL_CLOB"("ID") NOCHECK;     
ALTER TABLE "PUBLIC"."TBL_REP_INSTANCE" ADD CONSTRAINT "PUBLIC"."REP_INSTANCE_USER_FK" FOREIGN KEY("USER_FK") REFERENCES "PUBLIC"."TBL_USER"("ID") NOCHECK;   
ALTER TABLE "PUBLIC"."TBL_MENU" ADD CONSTRAINT "PUBLIC"."MENU_SELF_FK" FOREIGN KEY("SELF_FK") REFERENCES "PUBLIC"."TBL_MENU"("ID") NOCHECK;   
ALTER TABLE "PUBLIC"."TBL_CLOB" ADD CONSTRAINT "PUBLIC"."CLOB_ENV_UPDATED_FK" FOREIGN KEY("ENV_UPDATED_FK") REFERENCES "PUBLIC"."TBL_ENV"("ID") NOCHECK;      
ALTER TABLE "PUBLIC"."TBL_ORGANIZATION" ADD CONSTRAINT "PUBLIC"."ORGANIZATION_USER_FK" FOREIGN KEY("USER_CREATED_FK") REFERENCES "PUBLIC"."TBL_USER"("ID") NOCHECK;           
ALTER TABLE "PUBLIC"."TBL_PROFILE" ADD CONSTRAINT "PUBLIC"."PROFILE_ORGANIZATION_FK" FOREIGN KEY("ORG_FK") REFERENCES "PUBLIC"."TBL_ORGANIZATION"("ID") NOCHECK;              
ALTER TABLE "PUBLIC"."TBL_TASK_COMPONENT" ADD CONSTRAINT "PUBLIC"."ACTION_COMPONENT_FK" FOREIGN KEY("ACTION_FK") REFERENCES "PUBLIC"."TBL_ACTION"("ID") NOCHECK;              
ALTER TABLE "PUBLIC"."TBL_SESSION" ADD CONSTRAINT "PUBLIC"."SESSION_ORGANIZATION_FK" FOREIGN KEY("ORG_FK") REFERENCES "PUBLIC"."TBL_ORGANIZATION"("ID") NOCHECK;              
ALTER TABLE "PUBLIC"."TBL_REP_TEMPLATE" ADD CONSTRAINT "PUBLIC"."REP_TEMPLATE_XSL_CONTENT_FK" FOREIGN KEY("XSL_CONTENT_FK") REFERENCES "PUBLIC"."TBL_CLOB"("ID") NOCHECK;     
ALTER TABLE "PUBLIC"."TBL_TASK_FILE" ADD CONSTRAINT "PUBLIC"."TIPO_DOCUMENTO_ETAPA_CLOB_FK" FOREIGN KEY("TIPO_DOCUMENTO_ETAPA_FK") REFERENCES "PUBLIC"."TBL_TIPO_DOCUMENTO_ETAPA"("ID") NOCHECK;              
ALTER TABLE "PUBLIC"."TBL_CLOB" ADD CONSTRAINT "PUBLIC"."CLOB_ENV_FK" FOREIGN KEY("ENV_FK") REFERENCES "PUBLIC"."TBL_ENV"("ID") NOCHECK;      
ALTER TABLE "PUBLIC"."TBL_CONFIG_ENV" ADD CONSTRAINT "PUBLIC"."CONFIG_ENV_FK" FOREIGN KEY("ENV_FK") REFERENCES "PUBLIC"."TBL_ENV"("ID") NOCHECK;              
ALTER TABLE "PUBLIC"."TBL_REP_TEMPLATE" ADD CONSTRAINT "PUBLIC"."REP_TEMPLATE_XML_CONTENT_FK" FOREIGN KEY("XML_CONTENT_FK") REFERENCES "PUBLIC"."TBL_CLOB"("ID") NOCHECK;     
ALTER TABLE "PUBLIC"."TBL_PROFILE_TYPE" ADD CONSTRAINT "PUBLIC"."PROFILE_TYPE_ORG_FK" FOREIGN KEY("ORG_FK") REFERENCES "PUBLIC"."TBL_ORGANIZATION"("ID") NOCHECK;             
ALTER TABLE "PUBLIC"."TBL_TIPO_DOCUMENTO" ADD CONSTRAINT "PUBLIC"."TIPO_DOCUEMNTO_ENV_FK" FOREIGN KEY("ENV_FK") REFERENCES "PUBLIC"."TBL_ENV"("ID") NOCHECK;  
ALTER TABLE "PUBLIC"."TBL_TASK_ACCESS" ADD CONSTRAINT "PUBLIC"."TASK_ACCESS_PROFILE_TYPE_FK" FOREIGN KEY("PROF_FK") REFERENCES "PUBLIC"."TBL_PROFILE_TYPE"("ID") NOCHECK;     
ALTER TABLE "PUBLIC"."TBL_REP_INSTANCE" ADD CONSTRAINT "PUBLIC"."REP_INSTANCE_XML_CONTENT_FK" FOREIGN KEY("XML_CONTENT_FK") REFERENCES "PUBLIC"."TBL_CLOB"("ID") NOCHECK;     
