--INSERT INTO tbl_profile (type, type_fk, org_fk, prof_type_fk, user_fk) VALUES ('ENV', 1, 1, 2, 0);
--INSERT INTO tbl_profile (type, type_fk, org_fk, prof_type_fk, user_fk) VALUES ('ENV', 2, 2, 3, 0);
--INSERT INTO tbl_profile (type, type_fk, org_fk, prof_type_fk, user_fk) VALUES ('ENV', 3, 3, 4, 0);
--INSERT INTO tbl_profile (type, type_fk, org_fk, prof_type_fk, user_fk) VALUES ('PROF', 4, 3, 4, 0);
--INSERT INTO tbl_profile (type, type_fk, org_fk, prof_type_fk, user_fk) VALUES ('PROF', 2, 1, 2, 0);
--INSERT INTO tbl_profile (type, type_fk, org_fk, prof_type_fk, user_fk) VALUES ('PROF', 3, 2, 3, 0);